name: QA

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build all packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: install packages
        uses: ./.github/common-actions/install

      - name: build packages
        run: pnpm build

  eslint:
    name: lint all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: install packages
        uses: ./.github/common-actions/install

      - name: Run Build
        run: pnpm build

      - name: Run ESLint
        run: pnpm lint

  types:
    name: typecheck all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: install packages
        uses: ./.github/common-actions/install

      - name: run typecheck
        run: pnpm typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: install packages
        uses: ./.github/common-actions/install

      - name: Run prettier
        run: pnpm format:check
